<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="hand" params="connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${ns}_hand_joint" type="fixed">
        <parent link="${connected_to}" />
        <child link="${ns}_ft_sensor_link" />
        <origin xyz="${xyz}" rpy="${rpy}" />
      </joint>
    </xacro:unless>
    <link name="${ns}_ft_sensor_link">
      <visual>
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/ft-sensor.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0 0.01625" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${0.045+safety_distance}" length="0.0325" />
        </geometry>
      </collision>
    </link>

    <joint name="${ns}_ft_sensor_bracket_joint" type="fixed">
      <origin xyz="0 0 0.0325" rpy="0 0 0" />
      <parent link="${ns}_ft_sensor_link" />
      <child link="${ns}_bracket_link" />
    </joint>

    <link name="${ns}_bracket_link">
      <visual>
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/bracket.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${0.05+safety_distance}" length="0.02" />
        </geometry>
      </collision>
    </link>

    <joint name="${ns}_bracket_gripper_joint" type="fixed">
      <origin xyz="0 0 0.02" rpy="0 0 0" />
      <parent link="${ns}_bracket_link" />
      <child link="${ns}_gripper_link" />
    </joint>

    <link name="${ns}_gripper_link">
      <visual>
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/schunk-gripper.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0 0.0425" rpy="0 0 0" />
        <geometry>
          <box size="${0.07+safety_distance} ${0.216+safety_distance} 0.085" />
        </geometry>
      </collision>
    </link>

    <link name="${ns}_gripper_tcp" />
    <joint name="${ns}_gripper_tcp_joint" type="fixed">
      <origin xyz="0 0 0.085" rpy="0 0 0" />
      <parent link="${ns}_gripper_link" />
      <child link="${ns}_gripper_tcp" />
    </joint>

    <link name="${ns}_leftfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/schunk-finger.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0.015 0.0065" rpy="0 0 0" />
        <geometry>
          <box size="0.03 0.03 0.013" />
        </geometry>
      </collision>
    </link>
    <link name="${ns}_rightfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}" />
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/schunk-finger.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 -0.015 0.0065" rpy="0 0 0" />
        <geometry>
          <box size="0.03 0.03 0.013" />
        </geometry>
      </collision>
    </link>
    <joint name="${ns}_finger_joint1" type="prismatic">
      <parent link="${ns}_gripper_tcp" />
      <child link="${ns}_leftfinger" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="20" lower="0.0" upper="0.0575" velocity="0.2" />
    </joint>
    <joint name="${ns}_finger_joint2" type="prismatic">
      <parent link="${ns}_gripper_tcp" />
      <child link="${ns}_rightfinger" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 -1 0" />
      <limit effort="20" lower="0.0" upper="0.0575" velocity="0.2" />
      <mimic joint="${ns}_finger_joint1" />
    </joint>
    <link name="${ns}_lefttip">
      <visual>
        <origin xyz="0 0.0035 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/finger_tip.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0.0175 -0.06" rpy="0 0 0" />
        <geometry>
          <box size="0.03 0.025 0.12" />
        </geometry>
      </collision>
    </link>
    <link name="${ns}_righttip">
      <visual>
        <origin xyz="0 -0.0035 0" rpy="0 0 ${pi}" />
        <geometry>
          <mesh filename="package://rv7fm_description/meshes/rv7fm/visual/finger_tip.stl" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 -0.0175 -0.06" rpy="0 0 0" />
        <geometry>
          <box size="0.03 0.025 0.12" />
        </geometry>
      </collision>
    </link>
    <joint name="${ns}_fingertip_joint1" type="fixed">
      <parent link="${ns}_leftfinger" />
      <child link="${ns}_lefttip" />
      <origin xyz="0 0 0.1325" rpy="0 0 0" />
    </joint>
    <joint name="${ns}_fingertip_joint2" type="fixed">
      <parent link="${ns}_rightfinger" />
      <child link="${ns}_righttip" />
      <origin xyz="0 0 0.1325" rpy="0 0 0" />
    </joint>
  </xacro:macro>
</robot>
